dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}
  
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'

networks:
  rinkeby:
    verify: True
  development:
    verify: False